"""Change round to round_number

Revision ID: 034490ee6638
Revises: a0def24d1a76
Create Date: 2019-05-30 19:23:48.619283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034490ee6638'
down_revision = 'a0def24d1a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('round_number', sa.Integer(), nullable=False))
    op.drop_column('stats', 'round')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('stats', 'round_number')
    # ### end Alembic commands ###
