"""Remove round

Revision ID: 0909ffa4566e
Revises: 8f4e3993d071
Create Date: 2019-06-04 19:25:02.826115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0909ffa4566e'
down_revision = '8f4e3993d071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('round_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('stats_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], name='round_stats_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='round_pkey'),
    sa.UniqueConstraint('date', name='round_date_key'),
    sa.UniqueConstraint('round_no', name='round_round_no_key')
    )
    # ### end Alembic commands ###
