"""Remove date from Round for testing

Revision ID: 46bb21abf039
Revises: 64712555ede5
Create Date: 2019-06-18 19:39:08.683051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46bb21abf039'
down_revision = '64712555ede5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_round_date', table_name='round')
    op.drop_column('round', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_round_date', 'round', ['date'], unique=True)
    # ### end Alembic commands ###
