"""Make round unique

Revision ID: 512589ee4d52
Revises: 46bb21abf039
Create Date: 2019-06-18 19:40:48.509158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512589ee4d52'
down_revision = '46bb21abf039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'round', ['round_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'round', type_='unique')
    # ### end Alembic commands ###
