"""empty message

Revision ID: 571cfbef4d63
Revises: 7d55a8758b48
Create Date: 2019-06-10 19:49:28.099565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571cfbef4d63'
down_revision = '7d55a8758b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('round_round_no_key', 'round', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('round_round_no_key', 'round', ['round_no'])
    # ### end Alembic commands ###
