"""Swap relationship round-stats

Revision ID: 64712555ede5
Revises: 8ca164e11705
Create Date: 2019-06-18 19:37:17.864856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64712555ede5'
down_revision = '8ca164e11705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('round_stats_id_fkey', 'round', type_='foreignkey')
    op.drop_column('round', 'stats_id')
    op.add_column('stats', sa.Column('round_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stats', 'round', ['round_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_column('stats', 'round_id')
    op.add_column('round', sa.Column('stats_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('round_stats_id_fkey', 'round', 'stats', ['stats_id'], ['id'])
    # ### end Alembic commands ###
