"""Add relationship Round -> Stats;


Revision ID: 8ca164e11705
Revises: 909e1f92aa3a
Create Date: 2019-06-18 19:31:28.454187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca164e11705'
down_revision = '909e1f92aa3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('stats_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'round', 'stats', ['stats_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'round', type_='foreignkey')
    op.drop_column('round', 'stats_id')
    # ### end Alembic commands ###
