"""Add round to schema

Revision ID: 8f4e3993d071
Revises: 5567d853b236
Create Date: 2019-06-03 20:16:59.632699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4e3993d071'
down_revision = '5567d853b236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('round_no')
    )
    op.drop_column('stats', 'round_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('round_no', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('round')
    # ### end Alembic commands ###
