"""Add unique to round

Revision ID: 909e1f92aa3a
Revises: df6d065ccf7f
Create Date: 2019-06-18 19:27:53.871899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909e1f92aa3a'
down_revision = 'df6d065ccf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stats_place', table_name='stats')
    op.create_index(op.f('ix_stats_place'), 'stats', ['place'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_place'), table_name='stats')
    op.create_index('ix_stats_place', 'stats', ['place'], unique=False)
    # ### end Alembic commands ###
