"""Rugby table

Revision ID: 98be1acd33f4
Revises: 
Create Date: 2019-05-29 16:45:08.422366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98be1acd33f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rugby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rugby_team_name'), 'rugby', ['team_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rugby_team_name'), table_name='rugby')
    op.drop_table('rugby')
    # ### end Alembic commands ###
