"""Add complete stats

Revision ID: a4ec6a4d2e9d
Revises: d70a97371862
Create Date: 2019-06-19 06:03:47.285058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ec6a4d2e9d'
down_revision = 'd70a97371862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_round_round_no'), 'round', ['round_no'], unique=True)
    op.drop_constraint('round_round_no_key', 'round', type_='unique')
    op.add_column('stats', sa.Column('against_', sa.Integer(), nullable=False))
    op.add_column('stats', sa.Column('bonus_', sa.Integer(), nullable=False))
    op.add_column('stats', sa.Column('difference_', sa.Integer(), nullable=False))
    op.add_column('stats', sa.Column('drawn_', sa.Integer(), nullable=False))
    op.add_column('stats', sa.Column('for_', sa.Integer(), nullable=False))
    op.add_column('stats', sa.Column('lost_', sa.Integer(), nullable=False))
    op.add_column('stats', sa.Column('place_', sa.Integer(), nullable=False))
    op.add_column('stats', sa.Column('points_', sa.Integer(), nullable=False))
    op.add_column('stats', sa.Column('won_', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stats_place_'), 'stats', ['place_'], unique=False)
    op.create_index(op.f('ix_stats_points_'), 'stats', ['points_'], unique=False)
    op.drop_index('ix_stats_place', table_name='stats')
    op.drop_column('stats', 'place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_stats_place', 'stats', ['place'], unique=False)
    op.drop_index(op.f('ix_stats_points_'), table_name='stats')
    op.drop_index(op.f('ix_stats_place_'), table_name='stats')
    op.drop_column('stats', 'won_')
    op.drop_column('stats', 'points_')
    op.drop_column('stats', 'place_')
    op.drop_column('stats', 'lost_')
    op.drop_column('stats', 'for_')
    op.drop_column('stats', 'drawn_')
    op.drop_column('stats', 'difference_')
    op.drop_column('stats', 'bonus_')
    op.drop_column('stats', 'against_')
    op.create_unique_constraint('round_round_no_key', 'round', ['round_no'])
    op.drop_index(op.f('ix_round_round_no'), table_name='round')
    # ### end Alembic commands ###
