"""empty message

Revision ID: c49f56a59d07
Revises: ca8df45722f9
Create Date: 2019-05-31 11:25:03.019090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c49f56a59d07'
down_revision = 'ca8df45722f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('place', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_place'), 'post', ['place'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_post_place'), table_name='post')
    op.drop_column('post', 'place')
    # ### end Alembic commands ###
