"""empty message

Revision ID: c6a2841b0a60
Revises: af76c6956c95
Create Date: 2019-06-05 17:58:25.872376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a2841b0a60'
down_revision = 'af76c6956c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('round', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_round_date'), 'round', ['date'], unique=False)
    op.drop_constraint('round_date_key', 'round', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('round_date_key', 'round', ['date'])
    op.drop_index(op.f('ix_round_date'), table_name='round')
    op.alter_column('round', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
