"""empty message

Revision ID: ca8df45722f9
Revises: 8ca582fd4644
Create Date: 2019-05-31 11:22:48.937949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8df45722f9'
down_revision = '8ca582fd4644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('round_no', sa.Integer(), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_column('post', 'round_no')
    # ### end Alembic commands ###
