"""round_id in stats unique

Revision ID: de4a1ea122c9
Revises: 4fc9b4d10ec3
Create Date: 2019-06-18 20:03:52.417682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4a1ea122c9'
down_revision = '4fc9b4d10ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stats', ['round_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='unique')
    # ### end Alembic commands ###
