"""empty message

Revision ID: df6d065ccf7f
Revises: 571cfbef4d63
Create Date: 2019-06-10 19:54:38.186616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6d065ccf7f'
down_revision = '571cfbef4d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_round_date', table_name='round')
    op.create_index(op.f('ix_round_date'), 'round', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_round_date'), table_name='round')
    op.create_index('ix_round_date', 'round', ['date'], unique=False)
    # ### end Alembic commands ###
